// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv8HJWHETrUH-7NEb6d0lxVmdqAR5o5sc',
    appId: '1:912678992613:android:7aa87368d733fbb958f20c',
    messagingSenderId: '912678992613',
    projectId: 'rawaa-52354',
    storageBucket: 'rawaa-52354.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlEhLv1fiXOkQIj3MketT_cVIQd7W1z4A',
    appId: '1:912678992613:ios:efe28ed5cafd769558f20c',
    messagingSenderId: '912678992613',
    projectId: 'rawaa-52354',
    storageBucket: 'rawaa-52354.firebasestorage.app',
    iosBundleId: 'com.example.rawaaApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM4UilG0BDqIHWSrWQY6u5lkjK7l5t4UE',
    appId: '1:912678992613:web:b54832ca90cede7458f20c',
    messagingSenderId: '912678992613',
    projectId: 'rawaa-52354',
    authDomain: 'rawaa-52354.firebaseapp.com',
    storageBucket: 'rawaa-52354.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlEhLv1fiXOkQIj3MketT_cVIQd7W1z4A',
    appId: '1:912678992613:ios:efe28ed5cafd769558f20c',
    messagingSenderId: '912678992613',
    projectId: 'rawaa-52354',
    storageBucket: 'rawaa-52354.firebasestorage.app',
    iosBundleId: 'com.example.rawaaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM4UilG0BDqIHWSrWQY6u5lkjK7l5t4UE',
    appId: '1:912678992613:web:a0f367793c09ee6758f20c',
    messagingSenderId: '912678992613',
    projectId: 'rawaa-52354',
    authDomain: 'rawaa-52354.firebaseapp.com',
    storageBucket: 'rawaa-52354.firebasestorage.app',
  );

}